config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :act_plans
  resources :acts
  resources :allocations
  resources :axes
  resources :collective_decision_updates
  resources :collective_decisions
  resources :contract_updates
  resources :contractors
  resources :contracts
  resources :expence_forecasts
  resources :invoices
  resources :measures
  resources :organisations
  resources :payments
  resources :projects
  resources :schedule_actions
  resources :schedules
  resources :subprojects
  resources :targets
  resources :undertaking_certificates
  resources :users

  resource :session


  match '/login' => "sessions#new", :as => "login", via: [:get, :post]
  match '/logout' => "sessions#destroy", :as => "logout", via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root :to => "act_plans#index"

  root to: redirect('/act_plans/')

  get 'access_denied', to:'static#access_denied', as: :access_denied



end

app/views/00_act_plans_original/_form.html.haml
= simple_form_for(act_plan) do |f|
  - if act_plan.errors.any?
    #error_explanation
      - act_plan.errors.full_messages.each do |message|
        .alert.alert-danger{:role => "alert"}
          %span.glyphicon.glyphicon-exclamation-sign
          =message

  = f.input :code
  = f.input :description, as: :text
  = f.input :target_id, collection: @targets_for_select_box
  = f.button :submit, class:"btn btn-success"
  = link_to t(:cancel), 'javascript:history.go(-1);', class:"btn btn-danger pull-right"

app/views/00_act_plans_original/edit.html.haml
.page-header.h2= t(:edit_act_plan)
= render 'form', act_plan: @act_plan

app/views/00_act_plans_original/index.html.haml
%h2.sub-header= t(:act_plans)
= paginate @act_plans
.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th= t('act_plan.code')
        %th= t('act_plan.description')
        %th= t('act_plan.target')
    %tbody
      - @act_plans.each do |act_plan|
        %tr
          %td= link_to act_plan.code, act_plan
          %td= act_plan.description
          %td= link_to act_plan.target_code, target_path(act_plan.target_id), class: 'tooltips', title: act_plan.target_title
          %td= link_to "", edit_act_plan_path(act_plan), class: "tooltips glyphicon glyphicon-pencil", title: t(:edit)
          %td= link_to "", act_plan, method: :delete, data: { confirm: t(:act_plan_delete_confirmation) }, class: "tooltips glyphicon glyphicon-trash", title: t(:delete)
  = paginate @act_plans

= link_to t(:new_act_plan), new_act_plan_path, class:"btn btn-primary"

app/views/00_act_plans_original/new.html.haml
.page-header.h2= t(:new_act_plan)
= render 'form', act_plan: @act_plan

app/views/00_act_plans_original/show.html.haml
.page-header.h2= t(:show_act_plan)

= simple_form_for(@act_plan) do |f|
  = f.input :code, disabled: true
  = f.input :description, as: :text, disabled: true
  = f.input :target_id, as: :string, input_html: { value: @act_plan.target_full_title }, disabled: true

= link_to t(:edit), edit_act_plan_path(@act_plan), class:"btn btn-primary"
= link_to t(:back), act_plans_path, class:"btn btn-danger pull-right"