config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :act_plans
  resources :acts
  resources :allocations
  resources :axes
  resources :collective_decision_updates
  resources :collective_decisions
  resources :contract_updates
  resources :contractors
  resources :contracts
  resources :expence_forecasts
  resources :invoices
  resources :measures
  resources :organisations
  resources :payments
  resources :projects
  resources :schedule_actions
  resources :schedules
  resources :subprojects
  resources :targets
  resources :undertaking_certificates
  resources :users

  resource :session


  match '/login' => "sessions#new", :as => "login", via: [:get, :post]
  match '/logout' => "sessions#destroy", :as => "logout", via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root :to => "act_plans#index"

  root to: redirect('/act_plans/')

  get 'access_denied', to:'static#access_denied', as: :access_denied



end

app/models/target.rb
class Target < ApplicationRecord
  has_many :act_plans, :dependent => :destroy
  belongs_to :measure

  validates :code, presence: true, uniqueness: true
  validates :description, presence: true
  validates :measure_id, presence: true


  def full_title
    code + ": " + description
  end

  def measure_full_title
    measure.full_title
  end

  def measure_code
    measure.code
  end

  def measure_title
    measure.description
  end

end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :authenticate
  before_action :setup_measures_for_select_box
  before_action :set_target, only: [:show, :edit, :update, :destroy]
  before_action :add_breadcrumb_for_index

  load_and_authorize_resource

  # GET /targets
  # GET /targets.json
  def index
    @targets = Target.all.includes(:measure).page(params[:page]).per(20)
  end

  # GET /targets/1
  # GET /targets/1.json
  def show
    add_breadcrumb_for_show
  end

  # GET /targets/new
  def new
    add_breadcrumb_for_new
    @target = Target.new
  end

  # GET /targets/1/edit
  def edit
    add_breadcrumb_for_edit
  end

  # POST /targets
  # POST /targets.json
  def create
    @target = Target.new(target_params)

    respond_to do |format|
      if @target.save
        format.html { redirect_to @target, notice: t(:target_created) }
        format.json { render :show, status: :created, location: @target }
      else
        format.html { render :new }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /targets/1
  # PATCH/PUT /targets/1.json
  def update

    respond_to do |format|
      if @target.update(target_params)
        format.html { redirect_to @target, notice: t(:target_updated) }
        format.json { render :show, status: :ok, location: @target }
      else
        format.html { render :edit }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1
  # DELETE /targets/1.json
  def destroy
    @target.destroy
    respond_to do |format|
      format.html { redirect_to targets_url, notice: t(:target_deleted) }
      format.json { head :no_content }
    end
  end

  private

  def setup_measures_for_select_box
    @measures_for_select_box = Measure.all.collect { |mes| [mes.full_title, mes.id] }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_target
    @target = Target.find(params[:id])
  end

  # Never trust parameteract_plas from the scary internet, only allow the white list through.
  def target_params
    params.require(:target).permit(:code, :description, :measure_id)
  end
end

app/helpers/targets_helper.rb
module TargetsHelper

end

app/views/targets/_form.html.haml
= simple_form_for(target) do |f|
  - if target.errors.any?
    #error_explanation
      - target.errors.full_messages.each do |message|
        .alert.alert-danger{:role => 'alert'}
          %span.glyphicon.glyphicon-exclamation-sign
          =message

  = f.input :code
  = f.input :description, as: :text
  = f.input :measure_id, collection: @measures_for_select_box
  = f.button :submit, class:'btn btn-success'
  = link_to t(:cancel), 'javascript:history.go(-1);', class:'btn btn-danger pull-right'

app/views/targets/edit.html.haml
.page-header.h2= t(:edit_target)
= render 'form', target: @target

app/views/targets/index.html.haml
%h2.sub-header= t(:targets)
= paginate @targets
.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th= t('target.code')
        %th= t('target.description')
        %th= t('target.measure')
    %tbody
      - @targets.each do |target|
        %tr
          %td= link_to target.code, target
          %td= target.description
          %td= link_to target.measure_code, measure_path(target.measure_id), class: 'tooltips', title: target.measure_title
          %td= link_to "", edit_target_path(target), class: "tooltips glyphicon glyphicon-pencil", title: t(:edit)
          %td= link_to "", target, method: :delete, data: { confirm: t(:target_delete_confirmation) }, class: "tooltips glyphicon glyphicon-trash", title: t(:delete)
  = paginate @targets

= link_to t(:new_target), new_target_path, class:"btn btn-primary"

app/views/targets/new.html.haml
.page-header.h2= t(:new_target)
= render 'form', target: @target

app/views/targets/show.html.haml
.page-header.h2= t(:show_target)

= simple_form_for(@target) do |f|
  = f.input :code, disabled: true
  = f.input :description, as: :text, disabled: true
  = f.input :measure_id, as: :string, input_html: { value: @target.measure_full_title }, disabled: true

= link_to t(:edit), edit_target_path(@target), class:"btn btn-primary"
= link_to t(:back), targets_path, class:"btn btn-danger pull-right"