config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :act_plans
  resources :acts
  resources :allocations
  resources :axes
  resources :collective_decision_updates
  resources :collective_decisions
  resources :contract_updates
  resources :contractors
  resources :contracts
  resources :expence_forecasts
  resources :invoices
  resources :measures
  resources :organisations
  resources :payments
  resources :projects
  resources :schedule_actions
  resources :schedules
  resources :subprojects
  resources :targets
  resources :undertaking_certificates
  resources :users

  resource :session


  match '/login' => "sessions#new", :as => "login", via: [:get, :post]
  match '/logout' => "sessions#destroy", :as => "logout", via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root :to => "act_plans#index"

  root to: redirect('/act_plans/')

  get 'access_denied', to:'static#access_denied', as: :access_denied



end

app/models/allocation.rb
class Allocation < ApplicationRecord
  belongs_to :project

  monetize :amount_cents

  validates :protocol, presence: true, uniqueness: true
  validates :start_date, presence: true
  validates :amount_cents, presence: true
  validates :project_id, presence: true
  validates :amount, presence: true

  def project_full_title
    project.full_title
  end

  def project_title
    project.title
  end

  def project_code
    project.code
  end

  def full_title
    protocol + ": " + date + ": "+ amount_cents
  end


end

app/controllers/allocations_controller.rb
class AllocationsController < ApplicationController
  before_action :authenticate
  before_action :setup_projects_for_select_box
  before_action :set_allocation, only: [:show, :edit, :update, :destroy]
  before_action :add_breadcrumb_for_index

  load_and_authorize_resource

  # GET /allocations
  # GET /allocations.json
  def index
    @allocations = Allocation.all.includes(:project).page(params[:page]).per(20)
  end

  # GET /allocations/1
  # GET /allocations/1.json
  def show
    add_breadcrumb_for_show
  end

  # GET /allocations/new
  def new
    add_breadcrumb_for_new
    @allocation = Allocation.new
  end

  # GET /allocations/1/edit
  def edit
    add_breadcrumb_for_edit
  end

  # POST /allocations
  # POST /allocations.json
  def create
    @allocation = Allocation.new(allocation_params)

    respond_to do |format|
      if @allocation.save
        format.html { redirect_to @allocation, notice: t(:allocation_created) }
        format.json { render :show, status: :created, location: @allocation }
      else
        format.html { render :new }
        format.json { render json: @allocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allocations/1
  # PATCH/PUT /allocations/1.json
  def update

    respond_to do |format|
      if @allocation.update(allocation_params)
        format.html { redirect_to @allocation, notice: t(:allocation_updated) }
        format.json { render :show, status: :ok, location: @allocation }
      else
        format.html { render :edit }
        format.json { render json: @allocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allocations/1
  # DELETE /allocations/1.json
  def destroy
    @allocation.destroy
    respond_to do |format|
      format.html { redirect_to allocations_url, notice: t(:allocation_deleted) }
      format.json { head :no_content }
    end
  end

  private

  def setup_projects_for_select_box
    @projects_for_select_box = Project.all.collect { |pr| [pr.full_title, pr.id] }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_allocation
    @allocation = Allocation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def allocation_params
    params.require(:allocation).permit(:protocol, :start_date, :amount_cents, :amount, :project_id)
  end
end

app/helpers/allocations_helper.rb
module AllocationsHelper
end

app/views/allocations/_form.html.haml
= simple_form_for(allocation) do |f|
  - if allocation.errors.any?
    #error_explanation
      - allocation.errors.full_messages.each do |message|
        .alert.alert-danger{:role => 'alert'}
          %span.glyphicon.glyphicon-exclamation-sign
          =message

  = f.input :protocol, as: :string
  = f.input :start_date, as: :date
  = f.input :amount, as: :string
  = f.input :project_id, collection: @projects_for_select_box
  = f.button :submit, class:'btn btn-success'
  = link_to t(:cancel), 'javascript:history.go(-1);', class:'btn btn-danger pull-right'

app/views/allocations/edit.html.haml
.page-header.h2= t(:edit_allocation)
= render 'form', allocation: @allocation

app/views/allocations/index.html.haml
%h2.sub-header= t(:allocations)
= paginate @allocations
.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th= t('allocation.protocol')
        %th= t('allocation.start_date')
        %th= t('allocation.amount_cents')
        %th= t('allocation.project')
    %tbody
      - @allocations.each do |allocation|
        %tr
          %td= link_to allocation.protocol, allocation
          %td= allocation.start_date
          %td= allocation.amount
          %td= link_to allocation.project_code, project_path(allocation.project_id), class: 'tooltips', title: allocation.project_title
          %td= link_to "", edit_allocation_path(allocation), class: "tooltips glyphicon glyphicon-pencil", title: t(:edit)
          %td= link_to "", allocation, method: :delete, data: { confirm: t(:allocation_delete_confirmation) }, class: "tooltips glyphicon glyphicon-trash", title: t(:delete)
  = paginate @allocations

= link_to t(:new_allocation), new_allocation_path, class:"btn btn-primary"

app/views/allocations/new.html.haml
.page-header.h2= t(:new_allocation)
= render 'form', allocation: @allocation

app/views/allocations/show.html.haml
.page-header.h2= t(:show_allocation)

= simple_form_for(@allocation) do |f|
  = f.input :protocol, as: :string, disabled: true
  = f.input :start_date, as: :date, disabled: true
  = f.input :amount, as: :string, disabled: true
  = f.input :project_id, as: :string, input_html: { value: @allocation.project_full_title }, disabled: true

= link_to t(:edit), edit_allocation_path(@allocation), class:"btn btn-primary"
= link_to t(:back), allocations_path, class:"btn btn-danger pull-right"