config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :act_plans
  resources :acts
  resources :allocations
  resources :axes
  resources :collective_decision_updates
  resources :collective_decisions
  resources :contract_updates
  resources :contractors
  resources :contracts
  resources :expence_forecasts
  resources :invoices
  resources :measures
  resources :organisations
  resources :payments
  resources :projects
  resources :schedule_actions
  resources :schedules
  resources :subprojects
  resources :targets
  resources :undertaking_certificates
  resources :users

  resource :session


  match '/login' => "sessions#new", :as => "login", via: [:get, :post]
  match '/logout' => "sessions#destroy", :as => "logout", via: [:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root :to => "act_plans#index"

  root to: redirect('/act_plans/')

  get 'access_denied', to:'static#access_denied', as: :access_denied



end

app/models/project.rb
class Project < ApplicationRecord
  has_many :subprojects                      , :dependent => :destroy
  has_many :allocations                      , :dependent => :destroy
  has_one  :schedule  ,  as: :schedule_parent, :dependent => :destroy
  has_many :contracts,   as: :contract_parent, :dependent => :destroy

  belongs_to :act
  belongs_to :manager,            :class_name => 'User',          :foreign_key => 'manager_id'
  belongs_to :accountable,        :class_name => 'User',          :foreign_key => 'accountable_id'
  belongs_to :supervisor_body,    :class_name => 'Organisation',  :foreign_key => 'supervisor_body_id'
  belongs_to :collective_decision


  def full_title
    code + ": " + title
  end






end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:code, :title, :iis_code, :prefecture_code, :incorporation_date, :incorporation_protocol, :phase_code, :priority_code, :classification_code, :has_multiple_collective_decisions, :credit_first_quarter, :credit_second_quarter, :credit_third_quarter, :credit_fourth_quarter, :payments_until_last_year_according_to_sae, :IBAN, :expense_code, :PPI_payments, :proposed_credits, :credit_limit_of_implementation_body, :comments, :supervisor_body_id, :act_id, :collective_decision_id, :budget, :budget_history)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for(project) do |f|
  - if project.errors.any?
    #error_explanation
      %h2
        = pluralize(project.errors.count, "error")
        prohibited this project from being saved:
      %ul
        - project.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :code
    = f.text_field :code
  .field
    = f.label :title
    = f.text_area :title
  .field
    = f.label :iis_code
    = f.text_field :iis_code
  .field
    = f.label :prefecture_code
    = f.number_field :prefecture_code
  .field
    = f.label :incorporation_date
    -# = f.date_select :incorporation_date
  .field
    = f.label :incorporation_protocol
    = f.text_field :incorporation_protocol
  .field
    = f.label :phase_code
    = f.number_field :phase_code
  .field
    = f.label :priority_code
    = f.number_field :priority_code
  .field
    = f.label :classification_code
    = f.number_field :classification_code
  .field
    = f.label :has_multiple_collective_decisions
    = f.check_box :has_multiple_collective_decisions
  .field
    = f.label :credit_first_quarter
    = f.number_field :credit_first_quarter
  .field
    = f.label :credit_second_quarter
    = f.number_field :credit_second_quarter
  .field
    = f.label :credit_third_quarter
    = f.number_field :credit_third_quarter
  .field
    = f.label :credit_fourth_quarter
    = f.number_field :credit_fourth_quarter
  .field
    = f.label :payments_until_last_year_according_to_sae
    = f.number_field :payments_until_last_year_according_to_sae
  .field
    = f.label :IBAN
    = f.text_field :IBAN
  .field
    = f.label :expense_code
    = f.text_field :expense_code
  .field
    = f.label :PPI_payments
    = f.number_field :PPI_payments
  .field
    = f.label :proposed_credits
    = f.text_area :proposed_credits
  .field
    = f.label :credit_limit_of_implementation_body
    = f.number_field :credit_limit_of_implementation_body
  .field
    = f.label :comments
    = f.text_area :comments
  .field
    = f.label :supervisor_body_id
    = f.number_field :supervisor_body_id
  .field
    = f.label :act_id
    = f.number_field :act_id
  .field
    = f.label :collective_decision_id
    = f.number_field :collective_decision_id
  .field
    = f.label :budget
    = f.number_field :budget
  .field
    = f.label :budget_history
    = f.text_area :budget_history
  .actions
    = f.submit

app/views/projects/edit.html.haml
%h1 Editing Project
= render 'form', project: @project
= link_to 'Show', @project
|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
- @navigation_path = t(:project_details)

%div.projects

  -# %span.controls
    %span.red
      = link_to t(:delete), project_path(@project), :method => :delete, :confirm => t(:confirm_delete) if admin?
    = "|" if admin?
    = link_to t(:edit), edit_project_path(@project) if admin? or manager?



  .field
    %span.label
      = t('project.title') + ":"
    %span.data
      = @project.title

  .field
    %span.label
      = t('project.collective_decision') + ":"
    %span.data
      = link_to @project.collective_decision.full_title, @project.collective_decision if admin? or manager?
      = @project.collective_decision.full_title unless admin? or manager?
  .field
    %span.label
      = t('project.ppi_code') + ":"
    %span.data
      = @project.ppi_code

  .field
    %span.label
      = t('project.iis_code') + ":"
    %span.data
      = @project.iis_code

  .field
    %span.label
      = t('project.implementation_body') + ":"
    %span.data
      = link_to @project.implementation_body.department_name, @project.implementation_body

  .field
    %span.label
      = t('project.user') + ":"
    %span.data
      = link_to @project.user.full_name, @project.user if admin? or manager? or @project.user == cu
      = @project.user.full_name unless admin? or manager? or @project.user == cu

  .field
    %span.label
      = t('project.iban') + ":"
    %span.data
      = @project.iban

  .field
    %span.label
      = t('project.prefecture') + ":"
    %span.data
      = @project.prefecture_name

  .field
    %span.label
      = t('project.budget') + ":"
    %span.data
      = eu @project.budget

  .field
    %span.label
      = t('project.credit') + ":"
    %span.data
      = eu @project.credit

  .field
    %span.label
      = t('project.credit_date') + ":"
    %span.data
      = dt @project.credit_date

  .field
    %span.label
      = t('project.credit_protocol') + ":"
    %span.data
      = @project.credit_protocol

  .field
    %span.label
      = t('project.credit_tun') + ":"
    %span.data
      = link_to @project.credit_tun.force_encoding('UTF-8'), @project.credit_tun_link if @project.credit_tun

  .field
    %span.label
      = t('project.total_allocation') + ":"
    %span.data
      = eu @project.total_allocation

  .field
    %span.label
      = t('project.credit_limit') + ":"
    %span.data
      = eu @project.credit_limit

  .field
    %span.label
      = t('project.credit_balance') + ":"
    %span.data
      = eu @project.credit_balance

  .field
    %span.label
      = t('project.total_due') + ":"
    %span.data{:class => colorize_if_due(@project)}
      = eu @project.total_due

  .field
    %span.label.sub
      = t('project.due_30') + ":"
    %span.data{:class => colorize_if_due(@project)}
      = eu @project.due_30

  .field
    %span.label.sub
      = t('project.due_60') + ":"
    %span.data{:class => colorize_if_due(@project)}
      = eu @project.due_60

  .field
    %span.label.sub
      = t('project.due_90') + ":"
    %span.data{:class => colorize_if_due(@project)}
      = eu @project.due_90

  .field
    %span.label.sub
      = t('project.due_90_plus') + ":"
    %span.data{:class => colorize_if_due(@project)}
      = eu @project.due_90_plus

  .field
    %span.label
      = t('project.comments') + ":"
    %span.data
      = @project.comments

  .field
    %span.label
      = t :certificates
      \:
    %span.data_no_border
      %ul
        - @project.certificates.each do |certificate|
          %li
            = link_to certificate.full_title, certificate, class: colorize_if_due(certificate)
            %br

        .create_new_element
          = link_to t('new_certificate'), new_certificate_path(:pr_id => @project.id)

app/views/projects/new.html.haml
%h1 New Project
= render 'form', project: @project
= link_to 'Back', projects_path

app/views/projects/show.html.haml
 
%p
  %strong Code:
  = @project.code
%p
  %strong Title:
  = @project.title
%p
  %strong Iis code:
  = @project.iis_code
%p
  %strong Prefecture code:
  = @project.prefecture_code
%p
  %strong Incorporation date:
  = @project.incorporation_date
%p
  %strong Incorporation protocol:
  = @project.incorporation_protocol
%p
  %strong Phase code:
  = @project.phase_code
%p
  %strong Priority code:
  = @project.priority_code
%p
  %strong Classification code:
  = @project.classification_code
%p
  %strong Has multiple collective decisions:
  = @project.has_multiple_collective_decisions
%p
  %strong Credit first quarter:
  = @project.credit_first_quarter
%p
  %strong Credit second quarter:
  = @project.credit_second_quarter
%p
  %strong Credit third quarter:
  = @project.credit_third_quarter
%p
  %strong Credit fourth quarter:
  = @project.credit_fourth_quarter
%p
  %strong Payments until last year according to sae:
  = @project.payments_until_last_year_according_to_sae
%p
  %strong Iban:
  = @project.IBAN
%p
  %strong Expense code:
  = @project.expense_code
%p
  %strong Ppi payments:
  = @project.PPI_payments
%p
  %strong Proposed credits:
  = @project.proposed_credits
%p
  %strong Credit limit of implementation body:
  = @project.credit_limit_of_implementation_body
%p
  %strong Comments:
  = @project.comments
%p
  %strong Supervisor body:
  = @project.supervisor_body_id
%p
  %strong Act:
  = @project.act_id
%p
  %strong Collective decision:
  = @project.collective_decision_id
%p
  %strong Budget:
  = @project.budget
%p
  %strong Budget history:
  = @project.budget_history
= link_to 'Edit', edit_project_path(@project)
|
= link_to 'Back', projects_path